Elearner/Controllers/TopicTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Elearner.Models;

namespace Elearner.Controllers
{
    public class TopicTypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TopicTypes
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            return View(await db.TopicTypes.ToListAsync());
        }

        // GET: TopicTypes/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TopicType topicType = await db.TopicTypes.FindAsync(id);
            if (topicType == null)
            {
                return HttpNotFound();
            }
            return View(topicType);
        }

        // GET: TopicTypes/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: TopicTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "TopicTypeId,TopicTypeName")] TopicType topicType)
        {
            if (ModelState.IsValid)
            {
                db.TopicTypes.Add(topicType);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(topicType);
        }

        // GET: TopicTypes/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TopicType topicType = await db.TopicTypes.FindAsync(id);
            if (topicType == null)
            {
                return HttpNotFound();
            }
            return View(topicType);
        }

        // POST: TopicTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "TopicTypeId,TopicTypeName")] TopicType topicType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topicType).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(topicType);
        }

        // GET: TopicTypes/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TopicType topicType = await db.TopicTypes.FindAsync(id);
            if (topicType == null)
            {
                return HttpNotFound();
            }
            return View(topicType);
        }

        // POST: TopicTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TopicType topicType = await db.TopicTypes.FindAsync(id);
            db.TopicTypes.Remove(topicType);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Elearner/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Elearner.Models;

namespace Elearner.Controllers
{
    public class TopicsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Topics
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            var topics = db.Topics.Include(t => t.TopicType);
            return View(await topics.ToListAsync());
        }

        // GET: Topics/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = await db.Topics.FindAsync(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // GET: Topics/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.TopicTypeId = new SelectList(db.TopicTypes, "TopicTypeId", "TopicTypeName");
            return View();
        }

        // POST: Topics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "TopicId,TopicTypeId,TopicName")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Topics.Add(topic);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.TopicTypeId = new SelectList(db.TopicTypes, "TopicTypeId", "TopicTypeName", topic.TopicTypeId);
            return View(topic);
        }

        // GET: Topics/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = await db.Topics.FindAsync(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            ViewBag.TopicTypeId = new SelectList(db.TopicTypes, "TopicTypeId", "TopicTypeName", topic.TopicTypeId);
            return View(topic);
        }

        // POST: Topics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "TopicId,TopicTypeId,TopicName")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.TopicTypeId = new SelectList(db.TopicTypes, "TopicTypeId", "TopicTypeName", topic.TopicTypeId);
            return View(topic);
        }

        // GET: Topics/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = await db.Topics.FindAsync(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Topic topic = await db.Topics.FindAsync(id);
            db.Topics.Remove(topic);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Elearner/Controllers/UserTopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Elearner.Models;

namespace Elearner.Controllers
{
    public class UserTopicsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserTopics
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            var userTopics = db.UserTopics.Include(u => u.CourseTopic).Include(u => u.User);
            return View(await userTopics.ToListAsync());
        }

        // GET: UserTopics/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTopic userTopic = await db.UserTopics.FindAsync(id);
            if (userTopic == null)
            {
                return HttpNotFound();
            }
            return View(userTopic);
        }

        // GET: UserTopics/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CourseTopicId = new SelectList(db.CourseTopics, "CourseTopicId", "CourseTopicId");
            ViewBag.Id = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: UserTopics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "Id,CourseTopicId,UserTopicId,Completed")] UserTopic userTopic)
        {
            if (ModelState.IsValid)
            {
                db.UserTopics.Add(userTopic);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CourseTopicId = new SelectList(db.CourseTopics, "CourseTopicId", "CourseTopicId", userTopic.CourseTopicId);
            ViewBag.Id = new SelectList(db.ApplicationUsers, "Id", "FirstName", userTopic.Id);
            return View(userTopic);
        }

        // GET: UserTopics/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTopic userTopic = await db.UserTopics.FindAsync(id);
            if (userTopic == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseTopicId = new SelectList(db.CourseTopics, "CourseTopicId", "CourseTopicId", userTopic.CourseTopicId);
            ViewBag.Id = new SelectList(db.ApplicationUsers, "Id", "FirstName", userTopic.Id);
            return View(userTopic);
        }

        // POST: UserTopics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CourseTopicId,UserTopicId,Completed")] UserTopic userTopic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userTopic).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CourseTopicId = new SelectList(db.CourseTopics, "CourseTopicId", "CourseTopicId", userTopic.CourseTopicId);
            ViewBag.Id = new SelectList(db.ApplicationUsers, "Id", "FirstName", userTopic.Id);
            return View(userTopic);
        }

        // GET: UserTopics/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTopic userTopic = await db.UserTopics.FindAsync(id);
            if (userTopic == null)
            {
                return HttpNotFound();
            }
            return View(userTopic);
        }

        // POST: UserTopics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            UserTopic userTopic = await db.UserTopics.FindAsync(id);
            db.UserTopics.Remove(userTopic);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Elearner/Views/Courses/Create.cshtml
@model Elearner.Models.Course

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.CourseInformation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseInformation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseInformation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Elearner/Views/Courses/Delete.cshtml
@model Elearner.Models.Course

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CourseInformation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseInformation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Elearner/Views/Courses/Details.cshtml
@model Elearner.Models.Course

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CourseInformation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseInformation)            
        </dd>
    </dl>
</div>
<p>
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.CourseId })
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Elearner/Views/Courses/Edit.cshtml
@model Elearner.Models.Course

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CourseId)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.CourseInformation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseInformation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseInformation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Elearner/Views/Courses/Index.cshtml
@model IEnumerable<object>
    @{ 
        List<Elearner.Models.Course> lstCourses = Model.ToList()[0] as List<Elearner.Models.Course>;
        List<Elearner.Models.UserCourse> lstUserCourses = Model.ToList()[1] as List<Elearner.Models.UserCourse>;
        List<Elearner.Models.UserTopic> lstUserTopics = Model.ToList()[2] as List<Elearner.Models.UserTopic>;
        List<Elearner.Models.CourseTopic> lstCourseTopics = Model.ToList()[3] as List<Elearner.Models.CourseTopic>;
    }
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using Elearner.Models

@{
    ViewBag.Title = "Courses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Courses</h2>

@if (User.IsInRole("Admin"))
{
    var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
    var currentUser = manager.FindById(User.Identity.GetUserId());

        <p>
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Create New", "Create")
            }      
        </p>
        <table class="table" style="font-size:large">
            @foreach (var item in lstCourses)
            {
                <tr>
                    <td valign="middle">
                        @Html.DisplayFor(modelItem => item.CourseName)
                        <p style="font-size:small">@Html.DisplayFor(modelItem => item.CourseInformation)</p>
                        <p style="font-size:smaller">
                            @Html.ActionLink("Edit", "Edit", new { id = item.CourseId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.CourseId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.CourseId })
                        </p>
                    </td>
                </tr>
            }
        </table>
        @Html.ActionLink("Back to Manage Courses", "ManageCourses", "Courses")
}
else
{
    if (User.Identity.IsAuthenticated)
    {
        <table class="table" style="font-size:large">
            @foreach (var c in lstCourses)
            {
                <tr>
                    <td>
                        <strong>@Html.DisplayFor(modelItem => c.CourseName)</strong>
                        <p style="font-size:small">@Html.DisplayFor(modelItem => c.CourseInformation)</p>
                    </td>
                                        
                    <td>
                        @if (lstUserCourses == null || lstUserCourses.Count() == 0)
                        {
                            <button class="btn btn-info" type="button" id="enrollCourse" onclick="location.href='@Url.Action("Create", "EnrollCourse", new { id = c.CourseId })'">
                                START COURSE
                            </button>
                        }
                        else
                        {
                            if (lstUserCourses.Any(x => x.CourseId == c.CourseId && x.Completed == true))
                            {
                                <button class="btn btn-success" type="button" id="enrollCourse" onclick="location.href='@Url.Action("Create", "EnrollCourse", new { id = c.CourseId })'">
                                    COMPLETED
                                </button>
                            }
                            else if (lstUserCourses.Any(uc => uc.CourseId == c.CourseId && uc.Id == User.Identity.GetUserId()))
                            {
                                var percentage = (double)lstUserTopics.Where(x => x.Id == User.Identity.GetUserId() && x.CourseTopic.CourseId == c.CourseId).Count() / (double)lstCourseTopics.Where(w => w.CourseId == c.CourseId).Count() * 100;

                                <button class="btn btn-info" type="button" id="enrollCourse" onclick="location.href='@Url.Action("Create", "EnrollCourse", new { id = c.CourseId })'">
                                    CONTINUE - @percentage%
                                </button>
                            }
                            else
                            {
                                <button class="btn btn-primary" type="button" id="enrollCourse" onclick="location.href='@Url.Action("Create", "EnrollCourse", new { id = c.CourseId })'">
                                    START COURSE
                                </button>
                            }
                        }
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <p>
            Please @Html.ActionLink("SIGN UP", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" }) or
            @Html.ActionLink("LOG IN", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" }) to be able to start the course!
        </p>
    }
}

Elearner/Views/Courses/ManageCourses.cshtml
@model Elearner.Models.Course

@{
    ViewBag.Title = "ManageCourses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Content Manager</h2>


<div class="container text-justify">
    <div>
        <table class="table-striped" width="100%">
            <tr>
                <td>
                    <h4>Manage Admin Users:  @Html.ActionLink("Manage", "", "")</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <i>This page helps you to administer the site adminstrators</i>
                </td>
            </tr>
        </table>
    </div>
    <hr />
    <div>
        <table class="table-striped" width="100%">
            <tr>
                <td>
                    <h4>Courses:  @Html.ActionLink("Manage", "Index")</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <i>This page helps you to creat new Courses and manage existing ones</i>
                </td>
            </tr>

            <tr>
                <td>
                    <h4>Topic Types:  @Html.ActionLink("Manage", "Index", "TopicTypes")</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <i>This page helps you to setup and manage the Topic Types. A topic type for example can be a <strong>Beginner</strong> or <strong>Advanced</strong></i>
                </td>
            </tr>

            <tr>
                <td>
                    <h4>Topics:  @Html.ActionLink("Manage", "Index", "Topics")</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <i>This page helps you to creat new Topics and manage existing ones</i>
                </td>
            </tr>

            <tr>
                <td>
                    <h4>Course Topics:  @Html.ActionLink("Manage", "Index", "CourseTopics")</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <i>This page helps you to <strong>link</strong> a Course to a Topic and also manage existing ones</i>
                </td>
            </tr>

            <tr>
                <td>
                    <h4>Course Topic Sections:  @Html.ActionLink("Manage", "Index", "CourseTopicSections")</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <i>This page helps you to create the topic sections (topic learning content) and instruction (learning exercises) of a course topic and also manage existing ones</i>
                </td>
            </tr>

            <tr>
                <td>
                    <h4>User Courses:  @Html.ActionLink("Manage", "Index", "UserCourses")</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <i>....</i>
                </td>
            </tr>

            <tr>
                <td>
                    <h4>User Topics:  @Html.ActionLink("Manage", "Index", "UserTopics")</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <i>....</i>
                </td>
            </tr>
        </table>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}