Elearner/Controllers/CourseTopicSectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Elearner.Models;

namespace Elearner.Controllers
{
    public class CourseTopicSectionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CourseTopicSections
        public async Task<ActionResult> Index()
        {
            var courseTopicSections = db.CourseTopicSections.Include(c => c.CourseTopic);
            return View(await courseTopicSections.ToListAsync());
        }

        // GET: CourseTopicSections/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseTopicSection courseTopicSection = await db.CourseTopicSections.FindAsync(id);
            if (courseTopicSection == null)
            {
                return HttpNotFound();
            }
            return View(courseTopicSection);
        }

        // GET: CourseTopicSections/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CourseTopicId = new SelectList(db.CourseTopics, "CourseTopicId", "CourseTopicId");
            return View();
        }

        // POST: CourseTopicSections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "CourseTopicSectionId,CourseTopicId,CourseTopicSectionName,TopicSectionText,TopicSectionInstruction,Order")] CourseTopicSection courseTopicSection)
        {
            if (ModelState.IsValid)
            {
                db.CourseTopicSections.Add(courseTopicSection);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CourseTopicId = new SelectList(db.CourseTopics, "CourseTopicId", "CourseTopicId", courseTopicSection.CourseTopicId);
            return View(courseTopicSection);
        }

        // GET: CourseTopicSections/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseTopicSection courseTopicSection = await db.CourseTopicSections.FindAsync(id);
            if (courseTopicSection == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseTopicId = new SelectList(db.CourseTopics, "CourseTopicId", "CourseTopicId", courseTopicSection.CourseTopicId);
            return View(courseTopicSection);
        }

        // POST: CourseTopicSections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "CourseTopicSectionId,CourseTopicId,CourseTopicSectionName,TopicSectionText,TopicSectionInstruction,Order")] CourseTopicSection courseTopicSection)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseTopicSection).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CourseTopicId = new SelectList(db.CourseTopics, "CourseTopicId", "CourseTopicId", courseTopicSection.CourseTopicId);
            return View(courseTopicSection);
        }

        // GET: CourseTopicSections/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseTopicSection courseTopicSection = await db.CourseTopicSections.FindAsync(id);
            if (courseTopicSection == null)
            {
                return HttpNotFound();
            }
            return View(courseTopicSection);
        }

        // POST: CourseTopicSections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CourseTopicSection courseTopicSection = await db.CourseTopicSections.FindAsync(id);
            db.CourseTopicSections.Remove(courseTopicSection);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Elearner/Controllers/CoursesController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Elearner.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Identity;

namespace Elearner.Controllers
{
    public class CoursesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var user = User.Identity.GetUserId();

            List<object> myModel = new List<object>();
            myModel.Add(db.Courses.ToList());
            myModel.Add(db.UserCourses.Where(x=>x.Id.Equals(user)).ToList());
            myModel.Add(db.UserTopics.Where(x => x.Id.Equals(user)).ToList());
            myModel.Add(db.CourseTopics.ToList());

            return View(myModel);
        }

        // GET: ManageCourses
        [Authorize(Roles = "Admin")]
        public ActionResult ManageCourses()
        {
            return View();
        }

        // GET: Courses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Courses.FindAsync(id);

            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "CourseId,CourseName")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Courses.FindAsync(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "CourseId,CourseName")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = await db.Courses.FindAsync(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Course course = await db.Courses.FindAsync(id);
            db.Courses.Remove(course);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Elearner/Views/CourseTopicSections/Create.cshtml
@model Elearner.Models.CourseTopicSection

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CourseTopicSection</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseTopicId, "CourseTopicId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseTopicId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseTopicId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseTopicSectionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseTopicSectionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseTopicSectionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopicSectionText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TopicSectionText,30,100, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TopicSectionText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopicSectionInstruction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TopicSectionInstruction,20,100, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TopicSectionInstruction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Elearner/Views/CourseTopicSections/Delete.cshtml
@model Elearner.Models.CourseTopicSection

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CourseTopicSection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseTopic.CourseTopicId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseTopic.CourseTopicId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseTopicSectionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseTopicSectionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TopicSectionText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TopicSectionText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TopicSectionInstruction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TopicSectionInstruction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Elearner/Views/CourseTopicSections/Details.cshtml
@model Elearner.Models.CourseTopicSection

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CourseTopicSection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseTopic.CourseTopicId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseTopic.CourseTopicId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseTopicSectionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseTopicSectionName)
        </dd>

        <dt>
                @Html.DisplayNameFor(model => model.TopicSectionText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TopicSectionText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TopicSectionInstruction)
        </dt>

        <dd>
            @Html.DisplayNameFor(model => model.TopicSectionInstruction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CourseTopicSectionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Elearner/Views/CourseTopicSections/Edit.cshtml
@model Elearner.Models.CourseTopicSection

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CourseTopicSection</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CourseTopicSectionId)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseTopicId, "CourseTopicId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseTopicId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseTopicId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseTopicSectionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseTopicSectionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseTopicSectionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopicSectionText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TopicSectionText,30,100, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TopicSectionText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopicSectionInstruction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TopicSectionInstruction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TopicSectionInstruction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Elearner/Views/CourseTopicSections/Index.cshtml
@model IEnumerable<Elearner.Models.CourseTopicSection>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CourseTopic.CourseTopicId)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.CourseTopic.Topic.TopicName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.CourseTopicSectionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TopicSectionText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TopicSectionInstruction)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CourseTopic.CourseTopicId)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.CourseTopic.Topic.TopicName)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.CourseTopicSectionName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TopicSectionText)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TopicSectionInstruction)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Order)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CourseTopicSectionId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CourseTopicSectionId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CourseTopicSectionId })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@Html.ActionLink("Back to Manage Courses", "ManageCourses", "Courses")